"""empty message

Revision ID: 1e30ab23b61f
Revises: 488ce739fedd
Create Date: 2014-02-25 14:57:53.635471

"""

# revision identifiers, used by Alembic.
revision = '1e30ab23b61f'
down_revision = '488ce739fedd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('proceed_to_validation', sa.Boolean(), nullable=False, default=False))
    op.add_column('attempt', sa.Column('validation_started_at', sa.DateTime(), nullable=True))
    op.add_column('attempt', sa.Column('validation_ended_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'validation_started_at')
    op.drop_column('attempt', 'validation_ended_at')
    op.drop_column('attempt', 'proceed_to_validation')
    ### end Alembic commands ###
