"""add Attempt.is_expired attribute

Revision ID: 1f579a087211
Revises: 17ff13aef599
Create Date: 2014-06-05 17:48:04.678658

"""

# revision identifiers, used by Alembic.
revision = '1f579a087211'
down_revision = '17ff13aef599'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('is_expired', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'is_expired')
    ### end Alembic commands ###
