"""Add columns

Revision ID: a8e066255c5
Revises: bfd88f43c5d
Create Date: 2014-02-07 16:26:26.776349

"""

# revision identifiers, used by Alembic.
revision = 'a8e066255c5'
down_revision = 'bfd88f43c5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('checkout_started_at', sa.DateTime(), nullable=True))
    op.add_column('attempt', sa.Column('proceed_to_checkout', sa.Boolean(), nullable=False))
    op.add_column('attempt', sa.Column('queued_checkout', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'queued_checkout')
    op.drop_column('attempt', 'proceed_to_checkout')
    op.drop_column('attempt', 'checkout_started_at')
    ### end Alembic commands ###
