"""attempt.is_expired not nullable

Revision ID: c438ff7274b
Revises: 1f4dd1ce4476
Create Date: 2014-06-05 19:09:44.030001

"""

# revision identifiers, used by Alembic.
revision = 'c438ff7274b'
down_revision = '1f4dd1ce4476'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempt', 'is_expired',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempt', 'is_expired',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
